### ISSUE TITLE
Missing methods index

### ISSUE THREAD

**Issue by taviroquai** [jsdoc/jsdoc#1609]
Hi,

I can't understand why I have **no index of public methods** of class DB2Graphql.
Do I have to use a plugin?

Also, it seems that only the addMutation method is formatted within the class... 

Please se code in repo [https://github.com/taviroquai/db2graphql/blob/master/src/db2g.js](https://github.com/taviroquai/db2graphql/blob/master/src/db2g.js)

### Output

Please see output here [http://afonsodev.eu/docs/](http://afonsodev.eu/docs/)

### JSDoc configuration

Default config

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 8.15.0
| npm              | 6.4.1
| Operating system | Mint

Thanks!

**Comment by bbailleux** [comment]
Hello,

As far as I know, there is nothing in the default template _to display a methods list_.

Facing the same need, I tried to achieve that with the smallest change I can, with just a new section in one template and a new option to activate the "feature".

The result is as follow (note the "Methods" new menu) :

![Screenshot_2019-03-11 JSDoc Class DB2Graphql](https://user-images.githubusercontent.com/943793/54111369-fd6e1d00-43e3-11e9-81bd-3dbb6180bdb3.png)

I'd like to submit a PR to add the feature to JSDoc, since it is exclusively relying on a small optional change in the default template.

I may send you the corresponding code if you want, and am eager to know if the "JSDoc3 project is interested in applying the same modification to the upstream code.

Regards,
-- 
Benoît

**Comment by taviroquai** [comment]
@bbailleux
Thank you veru much for the info. A list of methods is so obvious that I thought that it should be visible by default along with the list of classes. And I thought I was doing something wrong!

Looks nice! Send me please. Is it in your fork? I can look into it.

Thanks!

**Comment by bbailleux** [comment]
@taviroquai 

Not yet in my (to be created) fork, because it is still a work in progress that needs to be refined and requires some documentation. But I will start to make it available (as a kind of "beta" version, or preview) for you ASAP.

Note that JSDoc own documentation is managed in a separate repo, so the related PR would have a different schedule...

**Comment by bbailleux** [comment]
@taviroquai 

I have pushed my small _patch_ into my fork.

Please see https://github.com/Orange-OpenSource/jsdoc/tree/patch-for-issue-1609 and the [related commit](https://github.com/Orange-OpenSource/jsdoc/commit/dbc64feec20fc78ca67bc3ddc0a54e375570a868)

To enable and test the feature, just add the `templates.default.includeMethodsIndex` config option.

For example, my own `jsdoc.conf.json` is as follow:

```json
{
  "plugins": ["plugins/markdown"],
  "opts": {
    "package": "./package.json",
    "readme": "./README.md",
    "recurse": true
  },
  "templates": {
    "default": {
      "includeMethodsIndex": true
    }
  }
}
```

(consider just the `templates` section)

Feedback really welcome!

**Comment by taviroquai** [comment]
Very nice. I'll try it as soon as possible. Thanks! 👍

**Comment by bbailleux** [comment]
@hegemonic 
Hello,
As this is nor a code change nor a change in the doc, is there any chance a PR with this minor template change would be accepted?

**Comment by bbailleux** [comment]
Hello @hegemonic @taviroquai 
Any news about the above question and proposal?

**Comment by taviroquai** [comment]
@bbailleux sorry didn't try yet.
@hegemonic please explain why was this issue closed. Not all are familiar with docjs.

**Comment by taviroquai** [comment]
@bbailleux I ended up creating a new template, added the methods index (like you showed in your fork), and I'm passing the parameter ```-t template/path``` when generatings the docs. It solved my issue!
