### ISSUE TITLE
Please bump major version when dropping support of older node versions

### ISSUE THREAD

**Issue by vsiakka** [jsdoc/jsdoc#1646]
Hi! With the release of 3.6.0 the minimum supported node version changed from 4 to 8.15.0. Because this change breaks the compatibility of the package with older node versions, I think it should be a major version bump. A major version bump would have prevented npm install failures for packages that depend `"jsdoc": "^3.0.0"` and use an older node version.

This is more of of a suggestion for future releases!

**Comment by MihaFriskovec** [comment]
You really should push this as a new MAJOR version.

For this package alone, there is a simple fix - set 3.5.5 version as fixed version in package.json. But there are many other packages out there that uses this package as their own dependency. For example, we are having trouble with angular-jsdoc. It automatically installs the latest version, meaning if your don't have node >=8.15.0, your app wont work. And there is no way around that.
Please, unpublish latest two versions, and push them as new 4.x.x version.

**Comment by hegemonic** [comment]
JSDoc has never followed semver. Sometimes there are breaking changes in minor versions. That's why the `README` encourages you to use the tilde (`~`) operator in `package.json` rather than the caret (`^`) operator.

I know that most people want JSDoc to adopt semver. For that reason, it's likely that 3.6.x will be the last minor version that includes breaking changes. However, I don't plan to unpublish 3.6.0 or 3.6.1.
