### ISSUE TITLE
fs.copyFileSync is not a function

### ISSUE THREAD

**Issue by applechips** [jsdoc/jsdoc#1671]
### Expected behavior
I can run `jsdoc -c ./jsdoc.conf.json` in my `npm run build:jsdoc` without an error saying `fs.copyFileSync is not a function` in ` node_modules\jsdoc\lib\jsdoc\fs.js:97` 

### Current behavior
I have upgraded my jsdoc from v3.5.5 to the latest, v3.6.3. when I try to build my solution, I get the error `fs.copyFileSync is not a function` in ` node_modules\jsdoc\lib\jsdoc\fs.js:97` when i run` npm run build:jsdoc`  which runs: `jsdoc -c ./jsdoc.conf.json`. how is this possible? i had to downgrade back to 3.5.5
![Screenshot (16)](https://user-images.githubusercontent.com/20119077/62900480-12423a00-bd0f-11e9-8282-1521f08e6403.png)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.6.3
| Node.js          | 10.15.3
| npm              | 6.4.1
| Operating system | Windows

**Comment by hegemonic** [comment]
In the screenshot you provided, the path to `lib\jsdoc\fs.js` includes the string `nodev6`. That makes me wonder if you're trying to run JSDoc with Node.js 6.x, not 10.15.3.

If so, that would explain the error, because `fs.copyFileSync()` was [added in Node.js 8.5.0](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_copyfilesync_src_dest_flags). That's one reason why JSDoc 3.6.3 requires Node.js >=8.15.0.

**Comment by siri-vi** [comment]
I had same error when i imported "fs/promises" instead of "fs"
