### ISSUE TITLE
Unable to install jsdoc

### ISSUE THREAD

**Issue by Raptor05** [jsdoc/jsdoc#1684]
I cannot install the JSDoc package since a few months now. Collegues of mine are having the same issue. I've already tried to install it on empty folders and also with different NPM and package versions.

```
PS C:\Users\mdeppe\Downloads\test> npm i jsdoc

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\mdeppe\Downloads\test\node_modules\uc.micro
npm ERR! dest C:\Users\mdeppe\Downloads\test\node_modules\.uc.micro.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\mdeppe\Downloads\test\node_modules\uc.micro' -> 'C:\Users\mdeppe\Downloads\test\node_modules\.uc.micro.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mdeppe\AppData\Roaming\npm-cache\_logs\2019-09-05T09_38_14_433Z-debug.log
```
[2019-09-05T09_42_27_444Z-debug.log](https://github.com/jsdoc/jsdoc/files/3578600/2019-09-05T09_42_27_444Z-debug.log)

Since it's an empty folder, there is no package.json or any JSDoc configuration.

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.6.3
| Node.js          | 10.16.2
| npm              | 6.10.3
| Operating system | Win 10 x64

**Comment by hegemonic** [comment]
As noted in krampstudio/grunt-jsdoc#188 and microsoft/vscode#13559, this issue is caused by a misbehaving virus scanner. Please contact the company that makes the virus scanner.

Alternatively, JSDoc requires the `uc.micro` package because it's a dependency of [markdown-it/markdown-it](https://github.com/markdown-it/markdown-it) and [markdown-it/linkify-it](https://github.com/markdown-it/linkify-it). You could try filing issues in those repos to see if the maintainers are willing to remove or replace the dependency.

JSDoc has already replaced its Markdown parser several times in the not-too-distant past, so I'd strongly prefer not to replace it again.

**Comment by maks232** [comment]
reported at mcafee
https://community.mcafee.com/t5/Enterprise-General-Discussions/McAfee-blocks-jsdoc/td-p/697154#.YZO1FSKn7Mo
