### ISSUE TITLE
Declare @type for multiple variables

### ISSUE THREAD

**Issue by Legends** [jsdoc/jsdoc#1733]
How can I achieve the following:

```
/**
 * @type {HTMLInputElement} 
 */
var minifiedNavCb, fixedHeaderCb, fixedNavCb, mobileNavCb;
```

Currently I only get the correct  intellisense for `minifiedNavCb`

**Comment by visj** [comment]
You can use [inline notations](https://github.com/google/closure-compiler/wiki/Annotating-Types#user-content-variable-declarations).

```js
var /** HTMLInputElement */ minifiedNavCb,
/** HTMLInputElement */ fixedHeaderCb, 
/** HTMLInputElement */fixedNavCb, 
/** HTMLInputElement */ mobileNavCb;
```

**Comment by Legends** [comment]
I don't like the repetition, would like to declare all of them in a single shot.
Anyways, `inline notations` don't work in my case and I use VsCode latest....

But using this notation style, I get full intellisense support:

```
/**
 * @type {HTMLInputElement} 
 */
var minifiedNavCb, fixedHeaderCb, fixedNavCb, mobileNavCb;
```

**Comment by visj** [comment]
Inline notations work fine for me using the latest JsDoc (3.6.3), they are correctly parsed and documented.

If your issue is with VsCode Intellisense, you should probably move this issue to the [Typescript repo](https://github.com/microsoft/TypeScript/issues) as it is not related to jsdoc, it's related to how Typescript parses jsdoc. [Here](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc) is a list of supported features i VSCode, you'll probably have to file a feature request for your requested functionality.

**Comment by Legends** [comment]
@visj 
`var /** HTMLInputElement */ fixedNavCb;`
Someone told me that this syntax is supported by Closure Compiler for type annotations, but not by TS UPD. TS supports other annotation.

I don't use google's closure compiler...

**Comment by MatthewPinheiro** [comment]
Though this was closed nearly a year ago, if @Legends or anyone else hasn't found a solution to this already, this may be a useful hack:
``` javascript
/**
 * @type {Array.<HTMLInputElement>}
 */
var [minifiedNavCb, fixedHeaderCb, fixedNavCb, mobileNavCb] = [];
```
This works with IntelliSense in Visual Studio Code v1.54.3 (the latest as of writing), and I'd imagine it probably works for older versions too. However, I have *not* tested this with standalone JSDoc, though I'd imagine it works with that too. Someone else will have to confirm.
