### ISSUE TITLE
jsdoc3 has no main entry point

### ISSUE THREAD

**Issue by 75lb** [jsdoc/jsdoc#691]
there is no [main](https://www.npmjs.org/doc/json.html#main) entry point in the jsdoc [package.json](https://github.com/jsdoc3/jsdoc/blob/master/package.json), are there any plans for one?  What's the current best practise for programmatic jsdoc use? 
https://github.com/75lb/jsdoc-to-markdown/issues/3

**Comment by Reinmar** [comment]
+1 from me for adding an entry point. In our case, we'd like to be able to inject our own reporter to one of the plugins which we wrote for JSDoc. With a CLI being the only entry point that'd need ugly hacks. That's also what https://www.npmjs.com/package/gulp-jsdoc3 needs to work around.

BTW, since we all agree that running JSDoc directly from Node.js would be very useful, why is this ticket closed? I understand that this is not on a roadmap, but it's a valid issue anyway.

**Comment by 75lb** [comment]
[jsdoc-api](https://github.com/jsdoc2md/jsdoc-api) is worth a look - gives you sync and async entry points, caching, supports html input and you can supply source directly as a string (if necessary)..  @Reinmar

**Comment by Reinmar** [comment]
Thanks for the hint. I'll take a look on it. But, TBH, after a long research we've chosen JSDoc for CKEditor 5 because it has a long history and for the same reason I wouldn't decide to use a fork of it. That's why I'd love if JSDoc had the entry point. Especially that we'll need to work on our own theme.

Out of curiosity – how much work did it require to open JSDoc, @75lb? Maybe there's a chance to merge back at least part of those changes.
